POST http://localhost:5000/api/content/add
content-type: application/json

{
    "title":"Test",
    "contentType":"book",
    "finished":true,
    "userId":"62497d3971382a2bac3edab1"
}

###
GET http://localhost:5000/api/content
Content-Type: application/json


{
    "userId": "62497d3971382a2bac3edab1" 
}

###
GET http://localhost:5000/api/content/finished

###
DELETE http://localhost:5000/api/content/delete/620f1c63c41c84535ff85fcc

###
PATCH http://localhost:5000/api/content/update/6211091a965b6532817e65fc
content-type: application/json

{
    "Finished":true
}

###
DELETE http://localhost:5000/api/content/delete


###
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
    "name":"Manish",
    "email":"hey@rqa.me",
    "password":"passwerd"
}